---
## tasks file for mywebrole
## Ajout ou suppression de users dans htaccess

- hosts: all
  vars_files:
      - ~/mywebrole/vars/main.yml

  tasks:

          - name: HTpasswd  Ajout de multiple Utilisateurs
            htpasswd:
                path: "{{ htpasswd_path }}"
                name: "{{ item }}"
                password: "{{ htaccess_passwd }}"
                owner: root
                group: root
                mode: 0644
            with_items:
                  - "{{ users }}"
            notify: httpd service
            tags:
              - addmUserHt

          - name: HTpasswd  Ajout dun Utilisateur
            htpasswd:
                path: "{{ htpasswd_path }}"
                name: "{{ htaccess_username }}"
                password: "{{ htaccess_passwd }}"
                owner: root
                group: root
                mode: 0644
            notify: httpd service
            tags:
              - addUserHt

          - name: HTpasswd Effacer Utilisateur
            htpasswd:
                path: "{{ htpasswd_path }}"
                name: "{{ htaccess_username }}"
                state: absent
            notify: httpd service
            tags:
              - rmvUserHt

  handlers:
          - name: Restart and enable httpd
            service:
               name: httpd
               state: restarted
               enabled: yes
            listen: httpd service
